import type { MenuItem } from "@/components/ui/MenuItemCard";

export type MenuCategory = {
  id: string;
  name: string;
  title: string;
  items: MenuItem[];
};

export const menuCategories: MenuCategory[] = [
  {
    id: "limited-time-offers",
    name: "Limited Time Offers",
    title: "Limited Time Offers",
    items: [
      {
        name: "Red Card Combo",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_bfddd6e4-94a9-40c2-a25b-a8238871eda2.png&width=420&quality=80&format=auto",
        description: "This Red Card Combo is bringing the heat all World Cup season long. Packed with a Mini Sweet & Spicy Chicken Bowl, crispy 3pc Chili Crisp Dumplings with fiery WaBlaze Sauce, and a refreshing Penalty Punch WaBeverage topped with juicy Mango Boba –This lineup was made for fans who don’t follow the rules, just the flavor!",
        price: "$9.99",
        calories: "",
        badge: "Limited Time",
      },
      {
        name: "Dragon Fruit Mango Lemonade w/ Mango Boba",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_c975c470-e235-474a-b35e-4750e0f3ccf0.png&width=420&quality=80&format=auto",
        description: "A winning blend of tangy lemonade, sweet dragon fruit, and juicy mango—made with real fruit and finished with a fresh lemon wedge. Topped with mango popping boba that burst with every sip for a flavor-packed “goal.”",
        calories: "",
        badge: "Limited Time",
      },
      {
        name: "Strawberry Watermelon Lemonade Energy Refresher w/ Mango Boba",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_e27cfa7d-550c-4855-a74a-80d6f6b9c14c.png&width=420&quality=80&format=auto",
        description: "A refreshing mix of real strawberry and watermelon with crisp lemonade and a boost of natural caffeine. Light, fruity, and energizing—finished with mango popping boba that deliver a juicy burst every time you score a sip.",
        calories: "",
        badge: "Limited Time",
      },
    ],
  },
  {
    id: "waba-favorites",
    name: "WaBa Favorites",
    title: "WaBa Favorites",
    items: [
      {
        name: "Chicken Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_50d8b2b0-cb5f-4a93-9c73-81d08d9e207d.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$10.69",
        calories: "590 Cals",
        badge: "Popular Item",
      },
      {
        name: "WaBa Chicken & Steak Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_4377f768-f322-4ade-886d-edc0e5718e94.jpg&width=420&quality=80&format=auto",
        description: "A popular pairing of our in-house marinated steak and our grilled all-natural chicken basted with our signature WaBa Sauce.",
        price: "$11.79",
        calories: "660 Cals",
        badge: "Popular Item",
      },
      {
        name: "Chicken Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_3bb6f908-c227-4f58-b597-fcf0bbeddcdc.png&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$12.69",
        calories: "820 Cals",
        badge: "Popular Item",
      },
      {
        name: "5 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_7e2726f3-6ddc-48ea-8d5a-2753201329a2.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$3.89",
        calories: "210 Cals",
        badge: "Popular Item",
      },
      {
        name: "Thai Tea",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_1e5e37b0-672a-4396-9bd0-f3a7e0f4fcac.jpg&width=420&quality=80&format=auto",
        description: "Premium black tea with cinnamon, cardamom, star anise, and lactose-free milk for a lightly sweet, refreshing treat.",
        calories: "240 Cals",
        badge: "Popular Item",
      },
      {
        name: "Chicken & Shrimp Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_ad8d761f-97b6-4365-8aa5-3a1a08daeed7.png&width=420&quality=80&format=auto",
        description: "A flavorful duo of tender shrimp and grilled all-natural chicken, lightly basted with our signature WaBa Sauce.",
        price: "$10.79",
        calories: "600 Cals",
        badge: "Popular Item",
      },
      {
        name: "Chicken & Shrimp Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_0151071e-4474-4675-8d21-4d3b355bf3b6.png&width=420&quality=80&format=auto",
        description: "A fresh dual-protein pairing of tender shrimp and grilled all-natural chicken, served the Signature WaBa Way with steamed veggies & WaBa Sauce. For a limited time only.",
        calories: "530-670 Cals",
        badge: "Popular Item",
      },
      {
        name: "5 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_769f02eb-e9f6-4e0e-91af-9aeb89f2dbc0.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$4.19",
        calories: "",
        badge: "Popular Item",
      },
    ],
  },
  {
    id: "tacos",
    name: "Tacos",
    title: "Tacos",
    items: [
      {
        name: "Mixed Taco Trio",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_3462dfef-fb72-43f3-b678-9fd3e82db09c.png&width=420&quality=80&format=auto",
        description: "Pick your trio: chicken, marinated steak, or shrimp, nestled in a corn and flour blend tortilla with Shredded Cabbage Blend, green onions, and spicy Boom Boom sauce.",
        calories: "510-720 Cals",
      },
      {
        name: "Taco Trio",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_29498c37-3835-409b-9831-7ed92748bd04.png&width=420&quality=80&format=auto",
        description: "Choose 3x grilled chicken, marinated steak, or shrimp tacos in a corn-flour blend tortilla with Shredded Cabbage Blend, green onions, and spicy Boom Boom sauce; plant-based options available.",
        calories: "510-720 Cals",
      },
      {
        name: "Tacos",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_b0cb1e13-b754-4387-aced-fcd48700d5cc.png&width=420&quality=80&format=auto",
        description: "Choose a grilled chicken, marinated steak, or shrimp taco in a corn-flour blend tortilla with Shredded Cabbage Blend, green onions, and spicy Boom Boom sauce.",
        calories: "170-240 Cals",
      },
    ],
  },
  {
    id: "rice-bowls",
    name: "Rice Bowls",
    title: "Rice Bowls",
    items: [
      {
        name: "WaBa Chicken & Steak Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_73c9eb73-764d-4d36-a7b3-4c6b98502c81.jpg&width=420&quality=80&format=auto",
        description: "A popular pairing of our in-house marinated steak and our grilled all-natural chicken basted with our signature WaBa Sauce.",
        price: "$10.79",
        calories: "710 Cals",
      },
      {
        name: "Steak Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8c79ce8d-ad3d-4880-a58d-7b44aa6e68d7.jpg&width=420&quality=80&format=auto",
        description: "Juicy steak marinated in house with our WaBa marinade and grilled to perfection.",
        price: "$10.79",
        calories: "720 Cals",
      },
      {
        name: "Chicken Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f104348c-9ac6-4932-99aa-000f749bb54f.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$9.69",
        calories: "640-760 Cals",
      },
      {
        name: "Sweet & Spicy Chicken Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f44d8c5d-5c05-4bcf-92c5-2d6dce4521dd.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with WaBa's sweet chili sauce.",
        price: "$9.69",
        calories: "680 Cals",
      },
      {
        name: "Salmon Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9d71b296-d740-4b24-9b70-bdd79f12743f.jpg&width=420&quality=80&format=auto",
        description: "Grilled wild-caught Pacific salmon basted with our signature WaBa sauce.",
        price: "$12.39",
        calories: "540 Cals",
      },
      {
        name: "Shrimp Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_af10eb8c-0085-46fd-a4ae-30f8a06d3c7c.png&width=420&quality=80&format=auto",
        description: "Grilled to perfection, tailless, fully peeled shrimp hand-basted with our signature WaBa sauce.",
        price: "$12.39",
        calories: "470 Cals",
      },
      {
        name: "Plantspired Steak Bowl ",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_84b0d4bc-c32e-4583-a1f1-f0efd73b2075.jpg&width=420&quality=80&format=auto",
        description: "Marinated plant-based steak slices fire-grilled-to-order.",
        price: "$10.79",
        calories: "660 Cals",
      },
      {
        name: "Tofu Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a48fce9d-edb0-4531-87f0-f748a8925dee.jpg&width=420&quality=80&format=auto",
        description: "Grilled organic tofu hand-basted in our flavorful signature WaBa sauce.",
        price: "$9.69",
        calories: "590 Cals",
      },
      {
        name: "Chicken & Shrimp Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a8a0515c-540d-429d-ac5a-dcdcf82cf4a4.png&width=420&quality=80&format=auto",
        description: "A flavorful duo of tender shrimp and grilled all-natural chicken, lightly basted with our signature WaBa Sauce.",
        price: "$10.79",
        calories: "600 Cals",
      },
    ],
  },
  {
    id: "bowl-packs",
    name: "Bowl Packs",
    title: "Bowl Packs",
    items: [
      {
        name: "Bowl Pack",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_17e99624-ff88-4ea3-b50b-56d4ec270b29.jpg&width=420&quality=80&format=auto",
        description: "Your choice of individual rice bowls with protein. Minimum 10 bowls required.",
        calories: "",
      },
      {
        name: "Veggie Bowl Pack",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a02e307c-14a2-47d0-9b57-02dd12713844.jpg&width=420&quality=80&format=auto",
        description: "Your choice of individual rice veggie bowls with protein. Minimum 10 bowls required.",
        calories: "",
      },
    ],
  },
  {
    id: "rice-veggie-bowls",
    name: "Rice Veggie Bowls",
    title: "Rice Veggie Bowls",
    items: [
      {
        name: "WaBa Chicken & Steak Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a0d885f7-1f68-4607-9d73-8378d5ffb50c.jpg&width=420&quality=80&format=auto",
        description: "A popular pairing of our in-house marinated steak and our grilled all-natural chicken basted with our signature WaBa Sauce.",
        price: "$11.79",
        calories: "660 Cals",
      },
      {
        name: "Steak Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_2cfc02b1-fc3a-45d8-ad90-2635a7a9335d.jpg&width=420&quality=80&format=auto",
        description: "Juicy steak marinated in-house with our WaBa marinade and grilled to perfection.",
        price: "$11.79",
        calories: "620 Cals",
      },
      {
        name: "Chicken Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_97f29546-0b54-47eb-a0a6-532c83d547d5.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$10.69",
        calories: "590 Cals",
      },
      {
        name: "Sweet & Spicy Chicken Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8f1025f9-2062-4a35-b24f-da3bf823539a.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with WaBa's sweet chili sauce.",
        price: "$10.69",
        calories: "640 Cals",
      },
      {
        name: "Salmon Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_0e53baf8-7cd8-4c56-be3b-b9ae7b0e5027.jpg&width=420&quality=80&format=auto",
        description: "Grilled wild-caught Pacific salmon basted with our signature WaBa sauce.",
        price: "$13.39",
        calories: "500 Cals",
      },
      {
        name: "Shrimp Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_baf126bb-d1b7-41e7-b16a-5b80f7744298.png&width=420&quality=80&format=auto",
        description: "Grilled to perfection, tailless, fully peeled shrimp hand-basted with our signature WaBa sauce.",
        price: "$13.39",
        calories: "420 Cals",
      },
      {
        name: "Plantspired Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_b2e01ee5-59a9-4ca7-9359-2c0614af0a92.jpg&width=420&quality=80&format=auto",
        description: "Marinated plant-based steak slices fire-grilled-to-order.",
        price: "$11.79",
        calories: "620 Cals",
      },
      {
        name: "Tofu Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_412f8111-2b71-48cd-900b-54d2d4ae0eb5.jpg&width=420&quality=80&format=auto",
        description: "Grilled organic tofu hand-basted in our flavorful signature WaBa sauce.",
        price: "$10.69",
        calories: "520 Cals",
      },
      {
        name: "Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9ffa314e-6a18-46e0-bdca-4836c4ac3443.jpg&width=420&quality=80&format=auto",
        description: "A combination of fresh carrots, broccoli, and cabbage steamed to the perfect crispness.",
        price: "$7.69",
        calories: "356 Cals",
      },
      {
        name: "Chicken & Shrimp Veggie Bowl",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8e632ff1-7e84-4178-9ac4-b9d5881d132f.png&width=420&quality=80&format=auto",
        description: "A fresh dual-protein pairing of tender shrimp and grilled all-natural chicken, served the Signature WaBa Way with steamed veggies & WaBa Sauce. For a limited time only.",
        calories: "",
      },
    ],
  },
  {
    id: "healthy-value-menu",
    name: "Healthy Value Menu",
    title: "Healthy Value Menu",
    items: [
      {
        name: "Value Bowl Combo",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_605b1a3e-39c7-446b-b286-afa320f49e95.png&width=420&quality=80&format=auto",
        description: "Choose one Mini Bowl, one value side & a small fountain drink.",
        price: "$9.49",
        calories: "362-398 Cals",
      },
      {
        name: "5 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_85b1899c-9db2-4a51-bcd4-aa426475a26b.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$3.89",
        calories: "175 Cals",
      },
      {
        name: "5 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_de9ad408-e5bd-4d53-b741-c1f4ab4c8182.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$4.19",
        calories: "",
      },
      {
        name: "Mini Bowls",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_04395fe1-1aa6-4f36-9d18-45385f507e21.jpg&width=420&quality=80&format=auto",
        description: "",
        calories: "290-320 Cals",
      },
      {
        name: "Loaded Miso Soups",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_91a6a7f7-490a-422d-baba-1653a1c3bb2b.jpg&width=420&quality=80&format=auto",
        description: "Our savory Miso Soup loaded with your choice of WaBa Grill’s signature grilled protein and rice.",
        calories: "150-160 Cals",
      },
      {
        name: "Side Salad",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_ab62c2e2-0584-4c42-bfb0-95999d6014c8.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$3.99",
        calories: "30 Cals",
      },
      {
        name: "Value Veggies",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_93561634-6cf7-4a7a-9c79-374676d59ebd.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$2.99",
        calories: "50 Cals",
      },
    ],
  },
  {
    id: "plates",
    name: "Plates",
    title: "Plates",
    items: [
      {
        name: "WaBa Chicken & Steak Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_e3dab2b0-abf7-43b2-881e-018cc333c5ed.png&width=420&quality=80&format=auto",
        description: "A popular pairing of our in-house marinated steak and our grilled all-natural chicken basted with our signature WaBa Sauce.",
        price: "$13.79",
        calories: "890 Cals",
      },
      {
        name: "Steak Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_0d6dbf90-34d5-4389-816c-98bb54aa58ce.png&width=420&quality=80&format=auto",
        description: "Juicy steak marinated in house with our WaBa marinade and grilled to perfection.",
        price: "$13.79",
        calories: "980 Cals",
      },
      {
        name: "Chicken Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_4b05e754-3000-478b-86bb-48b328b0d355.png&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$12.69",
        calories: "820 Cals",
      },
      {
        name: "Sweet & Spicy Chicken Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_d28bc958-fde4-4bb0-a2bf-2b1cfc8b018e.png&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with WaBa's sweet chili sauce.",
        price: "$12.69",
        calories: "860 Cals",
      },
      {
        name: "Salmon Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_5f8016e9-3c90-460a-8da4-ea328c9a4dc1.png&width=420&quality=80&format=auto",
        description: "Grilled wild-caught Pacific salmon basted with our signature WaBa sauce.",
        price: "$15.39",
        calories: "700 Cals",
      },
      {
        name: "Shrimp Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_2c3c2701-c85b-431d-950a-1b421ceb00b1.png&width=420&quality=80&format=auto",
        description: "Grilled to perfection, tailless, fully peeled shrimp hand-basted with our signature WaBa sauce.",
        price: "$15.39",
        calories: "570 Cals",
      },
      {
        name: "Plantspired Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9388eefd-2229-48f3-bdcb-8e39d763c409.png&width=420&quality=80&format=auto",
        description: "Marinated plant-based steak slices fire-grilled-to-order.",
        price: "$13.79",
        calories: "870 Cals",
      },
      {
        name: "Tofu Plate",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_ecdbfff8-789d-40b7-b23e-44da270983c1.png&width=420&quality=80&format=auto",
        description: "Grilled organic tofu hand-basted in our flavorful signature WaBa sauce.",
        price: "$12.69",
        calories: "740 Cals",
      },
    ],
  },
  {
    id: "family-meals",
    name: "Family Meals",
    title: "Family Meals",
    items: [
      {
        name: "Chicken & Steak Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f8638b3d-78c6-425f-9784-a03442964a06.jpg&width=420&quality=80&format=auto",
        description: "A popular pairing of our in-house marinated steak and our grilled all-natural chicken basted with our signature WaBa Sauce.",
        price: "$40.99",
        calories: "2350 Cals",
      },
      {
        name: "Marinated Steak Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_3d0da1f4-7540-4cfb-a758-afc9fd3080ef.jpg&width=420&quality=80&format=auto",
        description: "Juicy steak marinated in house with our WaBa marinade and grilled to perfection.",
        price: "$40.99",
        calories: "2400 Cals",
      },
      {
        name: "Chicken Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_51614165-5237-46fe-8adf-9d494fb6da08.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$32.99",
        calories: "2120 Cals",
      },
      {
        name: "Sweet & Spicy Chicken Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_fd529b5a-2961-47ae-b62b-7624affecb24.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with WaBa's sweet chili sauce.",
        price: "$32.99",
        calories: "1990 Cals",
      },
      {
        name: "White Meat Chicken Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_b6dacb44-78f0-4c8b-b60e-03a43302587e.jpg&width=420&quality=80&format=auto",
        description: "Grilled all-natural, never frozen chicken caramelized with our signature WaBa sauce.",
        price: "$35.99",
        calories: "1990 Cals",
      },
      {
        name: "White Meat Chicken & Marinated Steak Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9399c8cb-d999-415c-bc2e-f41b2591d2e0.jpg&width=420&quality=80&format=auto",
        description: "A popular pairing of grilled-all natural, never frozen chicken breast hand-basted with our signature WaBa sauce and our marinated steak.",
        price: "$41.99",
        calories: "2030 Cals",
      },
      {
        name: "Plantspired Steak Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_21e46ef6-e6ae-41ed-ac91-301751b307fe.jpg&width=420&quality=80&format=auto",
        description: "Marinated plant-based steak slices fire-grilled-to-order.",
        price: "$40.99",
        calories: "2400 Cals",
      },
      {
        name: "Organic Tofu Family Meal",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_bac6cc08-503f-42b3-8952-a525c637821f.jpg&width=420&quality=80&format=auto",
        description: "Grilled organic tofu hand-basted in our flavorful signature WaBa sauce.",
        price: "$32.99",
        calories: "1790 Cals",
      },
      {
        name: "20 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_de4c7e11-063f-44cc-bac4-d0338fe3871f.jpg&width=420&quality=80&format=auto",
        description: "20 savory pork and veggie-filled dumplings that are soft and crisp in all the right places.",
        price: "$14.99",
        calories: "840 Cals",
      },
      {
        name: "20 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_7a322d8e-8f22-4b40-a046-4aaaa2fc2904.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$15.89",
        calories: "",
      },
      {
        name: "Family Sized Salad",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_5fb80421-e1e2-4923-a017-a7ce98b98918.jpg&width=420&quality=80&format=auto",
        description: "A fresh leafy salad with carrots, and cucumber, served with a side of sweet & tangy WaBa Sesame dressing, serves 2.",
        price: "$6.69",
        calories: "360 Cals",
      },
      {
        name: "Family Sized Proteins",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_11e18e12-9a1f-4370-a094-fc1da39704d8.jpg&width=420&quality=80&format=auto",
        description: "Family-size sharable portions of your WaBa favorites.",
        calories: "720-1570 Cals",
      },
      {
        name: "Family Sized Veggies",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f30b32c2-1c3f-4dd6-ae88-0d404226c27d.jpg&width=420&quality=80&format=auto",
        description: "A selection of our Family Meal Veggies. Serves 4.",
        calories: "50-130 Cals",
      },
      {
        name: "Family Sized Rice",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_d2904699-cf29-4b22-967a-66469fd82b60.jpg&width=420&quality=80&format=auto",
        description: "A selection of our Family Meal Rices. Serves 4.",
        calories: "640-740 Cals",
      },
    ],
  },
  {
    id: "dumplings",
    name: "Dumplings",
    title: "Dumplings",
    items: [
      {
        name: "5 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_d5f6696a-b133-405d-8b44-6af6fad9bf36.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$3.89",
        calories: "210 Cals",
      },
      {
        name: "10 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_40466fc8-30ff-4794-a6e8-f6124b688bef.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$7.69",
        calories: "420 Cals",
      },
      {
        name: "20 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_3b6ce449-8893-4d4a-965c-1fed5c80c27a.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$14.99",
        calories: "840 Cals",
      },
      {
        name: "5 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_3ae2ccff-02fb-4773-b9a3-cfeb2d801690.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$4.19",
        calories: "",
      },
      {
        name: "10 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8370ef1c-6497-4c6a-bde0-84cc3cc98205.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$8.29",
        calories: "",
      },
      {
        name: "20 Chili Crisp Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_639b17e9-d474-416b-9825-20d3b529f8c3.jpg&width=420&quality=80&format=auto",
        description: "Discover our NEW Chili Crisp Dumplings, a bold new take on a WaBa classic! Our signature Pork and Veggie Dumplings are tossed in a fiery blend of chilies, sesame oil, crispy green onions, sesame seeds, and garlic.",
        price: "$15.89",
        calories: "",
      },
    ],
  },
  {
    id: "salads",
    name: "Salads",
    title: "Salads",
    items: [
      {
        name: "Spicy Asian Salad",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_930c7f5b-5ddc-4deb-bdbd-6c73dfdce4bb.jpg&width=420&quality=80&format=auto",
        description: "Arcadian blend salad topped with Cucumber & Edamame Kimchi, carrots, cilantro, and grilled White Meat chicken. Served with Spicy Sesame Dressing and wonton strips on the side.",
        calories: "420-700 Cals",
      },
      {
        name: "Signature House",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a4ad5adf-bce0-433d-8d98-3cda969d0079.jpg&width=420&quality=80&format=auto",
        description: "Arcadian blend salad topped with cucumber, carrots, and grilled white meat chicken. Served with WaBa’s Sesame Dressing and wonton strips on the side.",
        calories: "320-700 Cals",
      },
    ],
  },
  {
    id: "sides",
    name: "Sides",
    title: "Sides",
    items: [
      {
        name: "Proteins",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_22585633-bc85-4fe0-af1b-ffb8cb4369f2.png&width=420&quality=80&format=auto",
        description: "",
        calories: "50-290 Cals",
      },
      {
        name: "Veggies",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_7e8a3b97-f4df-432e-8ec5-f173be34c4d6.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$1.45",
        calories: "50 Cals",
      },
      {
        name: "Half-Ocado",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_e48f7e87-b716-4860-b508-774e97b3fc9e.jpg&width=420&quality=80&format=auto",
        description: "Side of avocado",
        price: "$2.69",
        calories: "150 Cals",
      },
      {
        name: "5 Dumplings",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_042e18ed-f4a5-4973-babb-5ab434fb6db2.jpg&width=420&quality=80&format=auto",
        description: "A savory veggie and pork filling encased in a soft, yet crisp wheat dough. Served with Sweet Chili Dipping Sauce.",
        price: "$3.89",
        calories: "210 Cals",
      },
      {
        name: "Miso Soup",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a5588764-2d89-42ac-82f4-d7112198444a.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$2.29",
        calories: "30 Cals",
      },
      {
        name: "Boom Boom Tacos",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_6bfd579b-5087-448c-9660-dd47af4d563f.png&width=420&quality=80&format=auto",
        description: "Choose a grilled chicken, marinated steak, or shrimp taco in a corn-flour blend tortilla with Shredded Cabbage Blend, green onions, and spicy Boom Boom sauce; plant-based options available.",
        calories: "170-240 Cals",
      },
      {
        name: "Side Salad",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_bdce7dd0-0001-4f99-8646-5f2b54c659c6.jpg&width=420&quality=80&format=auto",
        description: "Arcadian blend salad with, carrots, cucumber and cilantro and our Sesame dressing on the side.",
        price: "$3.99",
        calories: "190 Cals",
      },
      {
        name: "Edamame Kimchi",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_0f6465b8-d4b0-42f4-8c26-eb2cab944d79.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$2.09",
        calories: "100 Cals",
      },
      {
        name: "Side of Rice",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_11e228a6-5930-4e72-90da-2b9a7c778924.jpg&width=420&quality=80&format=auto",
        description: "White, brown or half-half.",
        calories: "320-370 Cals",
      },
      {
        name: "Sauces",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8643319a-c151-462c-9990-3fac2d281a73.jpg&width=420&quality=80&format=auto",
        description: "Forget secret sauces, we think our WaBa sauces deserve total recognition! Special blends of fruits and spices that make it sweet, savory, or spicy. These sauces offer a perfect balance or extra flavor to any WaBa dish.",
        calories: "50-60 Cals",
      },
      {
        name: "Side Wonton Strips",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9e92026b-9e34-479f-89e7-0597e50b20ec.jpg&width=420&quality=80&format=auto",
        description: "",
        price: "$0.79",
        calories: "75 Cals",
      },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    title: "Desserts",
    items: [
      {
        name: "Chocolate Chunk Cookie",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_cd07286f-7256-42ea-930f-c7af439f877c.jpg&width=420&quality=80&format=auto",
        description: "This brown butter cookie was crafted with non-GMO ingredients, cage free eggs, and pure cane sugar. It is chock full of decadent chocolate chunks and crunchy pretzel bits, a perfect combination of salty and sweet!",
        price: "$2.99",
        calories: "380 Cals",
      },
      {
        name: "Chewy Marshmallow Bar",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_21d0d5e0-bb82-440c-bdeb-fb24bbc3d562.jpg&width=420&quality=80&format=auto",
        description: "This sweet treat is made with crispy rice puffs, marshmallow cream, brown butter, sea salt, and even more mini marshmallows folded in! It’s certified gluten free and free of GMO’s and additives.",
        price: "$2.99",
        calories: "230 Cals",
      },
    ],
  },
  {
    id: "beverages",
    name: "Beverages",
    title: "Beverages",
    items: [
      {
        name: "Dragon Fruit Mango Lemonade",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_4d487be6-4c55-432a-90b6-b40a71fd22a6.jpg&width=420&quality=80&format=auto",
        description: "A perfect balance of tangy lemonade, sweet dragon fruit and juicy mango. Made with real fruits and topped with a fresh lemon wedge.",
        calories: "160-360 Cals",
      },
      {
        name: "Strawberry Watermelon Lemonade Energy Refresher",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_fc4a3dd9-6952-4a9a-aba0-a9ffccfdd265.jpg&width=420&quality=80&format=auto",
        description: "A refreshing mix of real strawberry and watermelon with crisp lemonade and natural caffeine. Fruity, light, and energizing—this flavorful refresher powers up any meal. Contains 56mg (Value), 88mg (Regular), 126mg (Large) caffeine.",
        calories: "160-350 Cals",
      },
      {
        name: "Thai Tea",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_6a0a55db-d919-4068-9883-f031ca6b9711.jpg&width=420&quality=80&format=auto",
        description: "Premium black tea with cinnamon, cardamom, star anise, and lactose-free milk for a lightly sweet, refreshing treat.",
        calories: "240 Cals",
      },
      {
        name: "Fountain Drink",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_b99d803a-90b4-40cb-8211-bf4e9b39210b.jpg&width=420&quality=80&format=auto",
        description: "",
        calories: "",
      },
      {
        name: "Aquafina - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f00abf26-9cc8-42be-904d-b0ec80ca1e2e.jpg&width=420&quality=80&format=auto",
        description: "Pure water for a perfect taste.",
        price: "$3.29",
        calories: "0 Cals",
      },
      {
        name: "Pepsi - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_b09529b8-8b81-4f61-a601-eec79fe3dec5.jpg&width=420&quality=80&format=auto",
        description: "The bold, refreshing, robust cola.",
        price: "$3.29",
        calories: "250 Cals",
      },
      {
        name: "Diet Pepsi - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a96dbc60-08e2-45a6-ba4c-3319a2ec6557.jpg&width=420&quality=80&format=auto",
        description: "A crisp tasting, refreshing pop of sweet, fizzy bubbles without calories.",
        price: "$3.29",
        calories: "0 Cals",
      },
      {
        name: "Aloe Vera Premium Drink",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_53350664-840f-4f26-ad37-5738f1b90b3b.jpeg&width=420&quality=80&format=auto",
        description: "A WaBa Better-For-You-Beverage",
        price: "$3.29",
        calories: "165 Cals",
      },
      {
        name: "Dole 100% Apple Juice - 15.2oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_9ae318cf-ed89-4928-9144-e680fd82c5eb.jpeg&width=420&quality=80&format=auto",
        description: "Dole apple juice is made with 100% juice and 100% of your daily Vitamin C",
        price: "$3.29",
        calories: "210 Cals",
      },
      {
        name: "Bubly Lime - 16oz Can",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_217d9454-d8b8-4487-858d-786e92a010b7.jpeg&width=420&quality=80&format=auto",
        description: "Lime flavored sparkling water - no calories, no sweeteners, all smiles.",
        price: "$3.29",
        calories: "0 Cals",
      },
      {
        name: "Dole Lemonade - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_f9b4956e-7c15-4665-94de-ffbae5fe29a7.jpeg&width=420&quality=80&format=auto",
        description: "Lemonade made with real lemon juice and real sugar",
        price: "$3.29",
        calories: "190 Cals",
      },
      {
        name: "Gatorade Fruit Punch - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_fbcdc8b0-06be-467f-961c-316ca14792c0.jpeg&width=420&quality=80&format=auto",
        description: "The thirst quenching taste of fruit punch to rehydrate and energize without caffeine",
        price: "$3.29",
        calories: "140 Cals",
      },
      {
        name: "Gatorade Cool Blue - 20oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_52e9185d-69c7-411a-b106-fc309e48a918.jpeg&width=420&quality=80&format=auto",
        description: "Cool, satisfying taste to quench thirst and energize without caffeine",
        price: "$3.29",
        calories: "140 Cals",
      },
      {
        name: "Pure Leaf Brewed Iced Tea Raspberry - 16.9oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_a82df1b0-cac1-4575-bfca-e96f92e63271.jpg&width=420&quality=80&format=auto",
        description: "Sweet and tangy raspberry pairs perfectly with classic iced tea.",
        price: "$3.29",
        calories: "",
      },
      {
        name: "Pure Leaf Brewed Iced Tea Unsweet - 16.9oz Bottle",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_925fd1d1-6d10-4ee1-b70e-5a00e74352d4.jpeg&width=420&quality=80&format=auto",
        description: "Iced tea brewed from real tea leaves steeped in water and bottled without adding sugar or color.",
        price: "$3.29",
        calories: "0 Cals",
      },
      {
        name: "Poppi Raspberry Rose - 12oz Can",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_5367c05e-7df3-4de5-9d03-e7539f094e51.png&width=420&quality=80&format=auto",
        description: "Mouthwatering flavor and all the soda feels. \r\nContains Apple Cider Vinegar and prebiotics from agave inulin and cassava root fiber. \r\n5g of sugar and 35 calories or less per can. \r\nPerfect for everyday, on-the-go refreshment or as a drink mixer. \r\nGreat alternative to diet soda soft drinks, kombucha, juice, seltzer & flavored water, energy drink, coconut water, tonic water, sports drinks, etc. \r\nVerified SHARK TANK brand.",
        price: "$2.99",
        calories: "30 Cals",
      },
      {
        name: "Poppi Strawberry Lemon - 12oz Can",
        image: "https://media.koala.io/resize?source=https://koala-api-production.s3.amazonaws.com/global-products/1x1_8d1ebb17-7365-4d48-b867-9bb93c82d30f.png&width=420&quality=80&format=auto",
        description: "Mouthwatering flavor and all the soda feels. \r\nContains Apple Cider Vinegar and prebiotics from agave inulin and cassava root fiber. \r\n5g of sugar and 35 calories or less per can. \r\nPerfect for everyday, on-the-go refreshment or as a drink mixer. \r\nGreat alternative to diet soda soft drinks, kombucha, juice, seltzer & flavored water, energy drink, coconut water, tonic water, sports drinks, etc. \r\nVerified SHARK TANK brand.",
        price: "$2.99",
        calories: "30 Cals",
      },
    ],
  },
];
